/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lrgs_domsatrecv_DomsatFranklin */

#ifndef _Included_lrgs_domsatrecv_DomsatFranklin
#define _Included_lrgs_domsatrecv_DomsatFranklin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lrgs_domsatrecv_DomsatFranklin
 * Method:    initFranklin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lrgs_domsatrecv_DomsatFranklin_initFranklin
  (JNIEnv *, jclass);

/*
 * Class:     lrgs_domsatrecv_DomsatFranklin
 * Method:    readPacket
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_lrgs_domsatrecv_DomsatFranklin_readPacket
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     lrgs_domsatrecv_DomsatFranklin
 * Method:    closeFranklin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lrgs_domsatrecv_DomsatFranklin_closeFranklin
  (JNIEnv *, jclass);

/*
 * Class:     lrgs_domsatrecv_DomsatFranklin
 * Method:    enable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lrgs_domsatrecv_DomsatFranklin_enable
  (JNIEnv *, jclass);

/*
 * Class:     lrgs_domsatrecv_DomsatFranklin
 * Method:    disable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lrgs_domsatrecv_DomsatFranklin_disable
  (JNIEnv *, jclass);

/*
 * Class:     lrgs_domsatrecv_DomsatFranklin
 * Method:    getErrorMsg
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_lrgs_domsatrecv_DomsatFranklin_getErrorMsg
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
