/*
*  $Id$
*
*  $Source$
*
*  $State$
*
*  $Log$
*  Revision 1.1  2008/04/04 18:21:10  cvs
*  Added legacy code to repository
*
*  Revision 1.2  2004/08/30 14:50:28  mjmaloney
*  Javadocs
*
*  Revision 1.1  2000/12/17 19:10:15  mike
*  *** empty log message ***
*
*
*/
package ilex.util;

/**
* This class forms the base for all exceptions generated by the Ilex, LRGS,
* and DECODES packages.
* This version is simply a place-holder. In the future, we will add a logging
* capability to the constructor so that all thrown exceptions can optionally
* be logged.
*/
public class IlexException extends Exception
{
	/**
	* Constructor
	* @param msg the message
	*/
	public IlexException( String msg )
	{
		super(msg);
	}
}

