
JSRC = \
    LoggerTester.java \
    TestEnum.java \
    TestEnumList.java \
    TestEnumListParser.java \
    TestEnumParser.java \
    TestEnumValue.java \
    TestEnumValueParser.java \
    Tester.java \
    XmlContentParser.java \
    XmlElementDescriptor.java \
    XmlFileParser.java \
    XmlObjectFactory.java \
    XmlObject.java \
    XmlParserTester.java

JCLASS = ${JSRC:.java=.class}

all: ${JCLASS}

include ${ILEXSRCROOT}/Makefile.Common

depends:
	touch make.depend

install:



realclean:  clean

scratch:  realclean all