#
#  $Id$
#
#  $State$
#
#  $Log$
#  Revision 1.1  2008/04/04 18:21:03  cvs
#  Added legacy code to repository
#
#  Revision 1.8  2003/11/20 18:33:39  mjmaloney
#  Created UnitsComboBox
#
#  Revision 1.7  2002/09/20 12:59:07  mjmaloney
#  SQL Dev.
#
#  Revision 1.6  2001/11/09 14:35:11  mike
#  dev
#
#  Revision 1.5  2001/10/26 13:03:23  mike
#  Added decoding to editor.
#
#  Revision 1.4  2001/09/19 01:11:56  mike
#  dev
#
#  Revision 1.3  2001/04/30 01:16:59  mike
#  dev
#
#  Revision 1.2  2001/04/21 01:28:40  mike
#  First runnable Unix version.
#
#  Revision 1.1  2001/04/20 20:27:35  mike
#  Removed import statements for borland classes
#
#

JSRC = \
	GuiApp.java \
	PropertiesEditDialog.java \
	PropertiesEditPanel.java \
	PropertyEditDialog.java \
	SortingListTable.java \
	SortingListTableModel.java \
	TableColumnAdjuster.java \
	TopFrame.java \
	EnumCellEditor.java \
	EnumComboBox.java \
	UnitsComboBox.java

JCLASS = ${JSRC:.java=.class}

all: ${JCLASS}

include ${DECODESSRCROOT}/Makefile.Common

depends:
	touch make.depend

install:

