#!/bin/bash

DH=/home/oracle/OPENDCS

#===========================================================================
# Run this script to install the CCP Schema on CWMS 3.0 Database
#===========================================================================
echo "This script installs CCP schema into an existing CWMS 3.0 database."
echo -n "Have you installed the CWMS V3.0 schema from HEC (y/n) ?"
read answer
if [ "$answer" != "y" ] && [ "$answer" != "Y" ]
then
  eche "Please install CWMS V3.0 from HEC before running this script."
  exit
fi

echo -n "IMPORTANT! Have you reviewed all settings in 'defines.sh' (y/n) ?"
read answer
if [ "$answer" != "y" ] && [ "$answer" != "Y" ]
then
  echo "Before running this script, edit defines.sh."
  exit
fi

#
# Source the defines file
#
if [ ! -f defines.sh ]
then
  echo "There is no 'defines.sh' in the current directory."
  echo "CD to the CCP's cwms30 schema directory before running this script."
  exit
fi
. defines.sh

echo -n "Running createDb.sh at " >$LOG
date >> $LOG
echo >> $LOG

echo "====================" >>$LOG
echo "Creating defines.sql" >>$LOG
echo "Creating defines.sql"
echo "-- defines.sql" >defines.sql
echo "-- Created automatically from 'defines.sh'. " >>defines.sql
echo "-- DO NOT EDIT THIS FILE" >>defines.sql
echo >>defines.sql
echo "undefine LOG;" >>defines.sql
echo "define LOG = $LOG;" >>defines.sql
echo "undefine TBL_SPACE_DIR;" >>defines.sql
echo "define TBL_SPACE_DIR = $TBL_SPACE_DIR;" >>defines.sql
echo "undefine TBL_SPACE_DATA;" >>defines.sql
echo "define TBL_SPACE_DATA = $TBL_SPACE_DATA;" >>defines.sql
echo "undefine TBL_SPACE_TEMP;" >>defines.sql
echo "define TBL_SPACE_TEMP = $TBL_SPACE_TEMP;" >>defines.sql
echo "undefine TBL_SPACE_SPEC;" >>defines.sql
echo "define TBL_SPACE_SPEC = 'tablespace $TBL_SPACE_DATA'" >>defines.sql
echo "undefine CCP_SCHEMA;" >>defines.sql
echo "define CCP_SCHEMA = $CCP_SCHEMA;" >>defines.sql
echo "undefine CCP_PASSWD;" >>defines.sql
echo "define CCP_PASSWD = $CCP_PASSWD;" >>defines.sql
echo "undefine USER_SCHEMA;" >>defines.sql
echo "define USER_SCHEMA = $USER_SCHEMA;" >>defines.sql
echo "undefine USER_PASSWD;" >>defines.sql
echo "define USER_PASSWD = $USER_PASSWD;" >>defines.sql
echo "define CWMS_SCHEMA = $CWMS_SCHEMA;" >>defines.sql
echo "define DBSUPER = $DBSUPER;" >>defines.sql
echo "define dflt_office_code = sys_context('CCPENV','CCP_OFFICE_CODE');" >>defines.sql

echo "====================" >>$LOG
echo "Creating tablespaces" >>$LOG
echo "Creating tablespaces"
rm -f tablespace.log
echo sqlplus $DBSUPER/$DBSUPER_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME as sysdba @tablespace.sql >>$LOG
sqlplus $DBSUPER/$DBSUPER_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME as sysdba @tablespace.sql
cat tablespace.log >>$LOG
rm tablespace.log

echo "======================" >>$LOG
echo "Creating roles & users" >>$LOG
echo "Creating roles & users"
rm -f roles.log
echo sqlplus $DBSUPER/$DBSUPER_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME as sysdba @roles.sql >>$LOG
sqlplus $DBSUPER/$DBSUPER_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME as sysdba @roles.sql
cat roles.log >>$LOG
rm roles.log

echo "======================" >>$LOG
echo "Running initialization as CWMS_20" >>$LOG
echo "Running initialization as CWMS_20"
rm -f cwmsAdmin.log
echo sqlplus $CWMS_SCHEMA/$CWMS_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @cwmsAdmin.sql >>$LOG
sqlplus $CWMS_SCHEMA/$CWMS_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @cwmsAdmin.sql >>$LOG
cat cwmsAdmin.log >>$LOG
rm cwmsAdmin.log

echo "=================================" >>$LOG
echo "Creating combined schema file ..." >>$LOG
echo "Creating combined schema file ..."
cp combined_hdr.sql combined.sql
cat opendcs.sql >> combined.sql
cat sequences.sql >>combined.sql
echo >> combined.sql
echo "-- Set Version Numbers" >> combined.sql
now=`date`
echo 'delete from DecodesDatabaseVersion; ' >> combined.sql
echo "insert into DecodesDatabaseVersion values(10, 'Installed $now');" >> combined.sql
echo 'delete from tsdb_database_version; ' >> combined.sql
echo "insert into tsdb_database_version values(9, 'Installed $now');" >> combined.sql
echo "spool off" >>combined.sql
echo "exit;" >> combined.sql

echo "======================" >>$LOG
echo "creating tables, indexes, and sequences" >>$LOG
echo "creating tables, indexes, and sequences"
rm -f combined.log
echo sqlplus $CCP_SCHEMA/$CCP_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @combined.sql >>$LOG
sqlplus $CCP_SCHEMA/$CCP_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @combined.sql
cat combined.log >>$LOG
rm combined.log
echo >>$LOG

echo "======================" >>$LOG
echo "Setting permissions" >>$LOG
echo "Setting permissions"
echo sqlplus $CCP_SCHEMA/$CCP_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @setPerms.sql >>$LOG
rm -f setPerms.log
sqlplus $CCP_SCHEMA/$CCP_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @setPerms.sql
cat setPerms.log >>$LOG
rm -f setPerms.log
echo >>$LOG

echo "======================" >>$LOG
echo "Creating packages cwms_ccp and cwms_ccp_vpd" >>$LOG
echo "Creating packages cwms_ccp and cwms_ccp_vpd"
rm -f pkg_cwms_ccp.log
echo sqlplus $CCP_SCHEMA/$CCP_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @pkg_cwms_ccp.sql >>$LOG
sqlplus $CCP_SCHEMA/$CCP_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @pkg_cwms_ccp.sql
cat pkg_cwms_ccp.log >>$LOG
rm -f pkg_cwms_ccp.log
echo >>$LOG

echo "======================" >>$LOG
echo "Creating vpd policy" >>$LOG
echo "Creating vpd policy"
rm -f vpd_policy.log
echo sqlplus $CCP_SCHEMA/$CCP_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @vpd_policy.sql >>$LOG
sqlplus $CCP_SCHEMA/$CCP_PASSWD@//$DBHOST:$DBPORT/$DB_TNSNAME @vpd_policy.sql
cat vpd_policy.log >>$LOG
rm -f vpd_policy.log
echo >>$LOG

echo "Left for you to do ..."
echo "  For each office that will use CCP on this database ..."
echo "     Create a CCP user with manager privilege in that office."
echo "     In the toolkit Setup menu, set URL, DB User and Password for that user."
echo "     In the Setup menu, set DbOfficeId appropriately."
echo "     CD to the directory containing this script and ..."
echo "     If you have a snapshot of that office's db, run dbimport -r filename"
echo "     Otherwise run the importDecodesTemplate.sh script in this directory."

rm defines.sql
