-- defines.sql
-- Created automatically from 'defines.sh'. 
-- DO NOT EDIT THIS FILE

undefine LOG;
define LOG = createdb.log;
undefine TBL_SPACE_DIR;
define TBL_SPACE_DIR = /opt/app/oracle/oradata/cwms30;
undefine TBL_SPACE_DATA;
define TBL_SPACE_DATA = CCP_DATA;
undefine TBL_SPACE_TEMP;
define TBL_SPACE_TEMP = CCP_TEMP;
undefine TBL_SPACE_SPEC;
define TBL_SPACE_SPEC = 'tablespace CCP_DATA'
undefine CCP_SCHEMA;
define CCP_SCHEMA = CCP;
undefine CCP_PASSWD;
define CCP_PASSWD = CCP;
undefine USER_SCHEMA;
define USER_SCHEMA = CCPUSER;
undefine USER_PASSWD;
define USER_PASSWD = xxxxxxx;
define CWMS_SCHEMA = CWMS_20;
define DBSUPER = SYS;
define dflt_office_code = sys_context('CCPENV','CCP_OFFICE_CODE');
define DEFAULT_OFFICE_ID = 'SPA';
