#
#  $Id$
#
#  $Log$
#  Revision 1.1  2008/04/04 18:21:04  cvs
#  Added legacy code to repository
#
#  Revision 1.5  2004/04/12 21:30:34  mjmaloney
#  dev
#
#  Revision 1.4  2004/04/02 15:50:46  mjmaloney
#  Implemented EU editing functions.
#
#  Revision 1.3  2004/04/01 22:37:24  mjmaloney
#  Implemented controls for enumerations.
#
#  Revision 1.2  2004/02/03 15:19:55  mjmaloney
#  Working GUI prototype complete.
#
#  Revision 1.1  2004/02/02 22:12:57  mjmaloney
#  dev.
#
#

JSRC = \
	RefListEditor.java \
	RefListFrame.java \
	RefListFrame_AboutBox.java \
	EnumTableModel.java \
	EUTableModel.java \
	EUCnvTableModel.java \
	EUCnvEditDialog.java \
	DTEquivTableModel.java \
	EnumValueDialog.java \
	EUDialog.java \
	DTEDialog.java


JCLASS = ${JSRC:.java=.class}

all: ${JCLASS}

include ${DECODESSRCROOT}/Makefile.Common

depends:
	touch make.depend

install:

