package decodes.cwms.algo;

import java.util.Date;
import java.util.NavigableMap;
import java.util.TreeMap;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Database-free checks of the calculations for InflowEstimationAlgo:
 * Inflow = Average(Release) + d(Storage)/dt + Sum(Average(Outflows))
 *
 * These are not comparisons against values generated by the algorithm. Each
 * expected value is calculated independently on paper and written beside its
 * assertion. That makes a failure useful: it means the production calculation
 * no longer implements the documented equation. Values are in cubic metres,
 * cubic metres per second, and seconds as appropriate.
 */
final class InflowEstimationAlgoMathTest
{
	private static final long HOUR_SECONDS = 60 * 60;
	private static final long THREE_HOURS_SECONDS = 3 * HOUR_SECONDS;
	private static final Date END = new Date(THREE_HOURS_SECONDS * 1000L);

	@Test
	void calculatesDirectInflowFromReleaseStorageAndAdditionalOutflow() throws Exception
	{
		// The output is at hour 3, so each three-hour input window is [hour 0, hour 3].
		// End-of-period samples represent the value for the preceding interval.
		NavigableMap<Long, Double> release = endOfPeriodValues(10.0, 20.0, 30.0);
		NavigableMap<Long, Double> storage = valuesAt(0, 1_000.0, THREE_HOURS_SECONDS, 4_600.0);
		NavigableMap<Long, Double> outflow = endOfPeriodValues(2.0, 3.0, 4.0);

		double averageRelease = InflowEstimationAlgo.averageEndOfPeriodValues(release, END, THREE_HOURS_SECONDS);
		double storageChange = InflowEstimationAlgo.calculateStorageChangeRate(storage, END, THREE_HOURS_SECONDS);
		double averageOutflow = InflowEstimationAlgo.averageEndOfPeriodValues(outflow, END, THREE_HOURS_SECONDS);

		// Independently derived expected terms:
		// release = (10 + 20 + 30) / 3 = 20 cms
		// storage = (4,600 - 1,000) m3 / 10,800 s = 1/3 cms
		// outflow = (2 + 3 + 4) / 3 = 3 cms
		// inflow = 20 + 1/3 + 3 = 23 1/3 cms.
		assertEquals(20.0, averageRelease, 1e-9);
		assertEquals(1.0 / 3.0, storageChange, 1e-9);
		assertEquals(3.0, averageOutflow, 1e-9);
		assertEquals(23.0 + 1.0 / 3.0, averageRelease + storageChange + averageOutflow, 1e-9);
	}

	@Test
	void weightsIrregularEndOfPeriodValuesByTheirElapsedDuration() throws Exception
	{
		NavigableMap<Long, Double> release = valuesAt(
				30 * 60, 10.0,
				2 * HOUR_SECONDS, 40.0,
				THREE_HOURS_SECONDS, 70.0);

		// Do not calculate an arithmetic mean here: the observations cover unequal
		// durations. 10 applies for 30 min, 40 for 90 min, and 70 for 60 min:
		// (10 * 0.5 + 40 * 1.5 + 70 * 1.0) / 3.0 = 45 cms.
		assertEquals(45.0, InflowEstimationAlgo.averageEndOfPeriodValues(release, END, THREE_HOURS_SECONDS), 1e-9);
	}

	@Test
	void interpolatesStorageAtWindowBoundariesBeforeCalculatingChangeRate() throws Exception
	{
		NavigableMap<Long, Double> storage = valuesAt(
				0, 1_000.0,
				2 * HOUR_SECONDS, 2_200.0,
				4 * HOUR_SECONDS, 3_400.0);
		Date threeHourEnd = new Date(3 * HOUR_SECONDS * 1000L);

		// The requested boundaries fall between samples. Linear interpolation gives
		// 1,600 m3 at hour 1 and 2,800 m3 at hour 3; delta 1,200 m3 / 7,200 s = 1/6 cms.
		assertEquals(1.0 / 6.0,
				InflowEstimationAlgo.calculateStorageChangeRate(storage, threeHourEnd, 2 * HOUR_SECONDS), 1e-9);
	}

	private static NavigableMap<Long, Double> endOfPeriodValues(double... values)
	{
		NavigableMap<Long, Double> result = new TreeMap<>();
		for(int i = 0; i < values.length; i++)
		{
			result.put((i + 1L) * HOUR_SECONDS * 1000L, values[i]);
		}
		return result;
	}

	private static NavigableMap<Long, Double> valuesAt(Object... timeValuePairs)
	{
		NavigableMap<Long, Double> result = new TreeMap<>();
		for(int i = 0; i < timeValuePairs.length; i += 2)
		{
			result.put(((Number) timeValuePairs[i]).longValue() * 1000L,
					((Number) timeValuePairs[i + 1]).doubleValue());
		}
		return result;
	}
}
