------------------------------------------------------------------------------
-- OpenDCS Alarm Tables for Oracle
------------------------------------------------------------------------------

CREATE TABLE ALARM_DEF
(
	ALARM_DEF_ID INT NOT NULL,
	ALARM_GROUP_ID INT NOT NULL,
	LOADING_APPLICATION_ID INT NOT NULL,
	PRIORITY INT NOT NULL,
	PATTERN varchar2(256),
	PRIMARY KEY (ALARM_DEF_ID)
) &TBL_SPACE_SPEC;


CREATE TABLE ALARM_GROUP
(
	ALARM_GROUP_ID INT NOT NULL,
	ALARM_GROUP_NAME VARCHAR2(32) NOT NULL UNIQUE,
	LAST_MODIFIED NUMBER(19) NOT NULL,
	PRIMARY KEY (ALARM_GROUP_ID)
) &TBL_SPACE_SPEC;


CREATE TABLE EMAIL_ADDR
(
	ALARM_GROUP_ID INT NOT NULL,
	ADDR VARCHAR2(256) NOT NULL,
	PRIMARY KEY (ALARM_GROUP_ID, ADDR)
) &TBL_SPACE_SPEC;


CREATE TABLE FILE_MONITOR
(
	ALARM_GROUP_ID INT NOT NULL,
	PATH VARCHAR2(256) NOT NULL,
	PRIORITY INT NOT NULL,
	MAX_FILES int,
	MAX_FILES_HINT VARCHAR2(128),
	-- Maximum Last Modify Time
	MAX_LMT VARCHAR2(32),
	MAX_LMT_HINT VARCHAR2(128),
	ALARM_ON_DELETE VARCHAR2(5),
	ON_DELETE_HINT VARCHAR2(128),
	MAX_SIZE NUMBER(19),
	MAX_SIZE_HINT VARCHAR2(128),
	ALARM_ON_EXISTS VARCHAR2(5),
	ON_EXISTS_HINT VARCHAR2(128),
	ENABLED VARCHAR2(5),
	PRIMARY KEY (ALARM_GROUP_ID, PATH)
) &TBL_SPACE_SPEC;


CREATE TABLE PROCESS_MONITOR
(
	ALARM_GROUP_ID INT NOT NULL,
	LOADING_APPLICATION_ID INT NOT NULL,
	ENABLED VARCHAR2(5),
	PRIMARY KEY (ALARM_GROUP_ID, LOADING_APPLICATION_ID)
) &TBL_SPACE_SPEC;



/* Create Foreign Keys */

ALTER TABLE PROCESS_MONITOR
	ADD CONSTRAINT PROCESS_MONITOR_FK1
	FOREIGN KEY (ALARM_GROUP_ID)
	REFERENCES ALARM_GROUP (ALARM_GROUP_ID)
;


ALTER TABLE FILE_MONITOR
	ADD CONSTRAINT FILE_MONITOR_FK1
	FOREIGN KEY (ALARM_GROUP_ID)
	REFERENCES ALARM_GROUP (ALARM_GROUP_ID)
;


ALTER TABLE EMAIL_ADDR
	ADD CONSTRAINT EMAIL_ADDR_FK1
	FOREIGN KEY (ALARM_GROUP_ID)
	REFERENCES ALARM_GROUP (ALARM_GROUP_ID)
;


ALTER TABLE ALARM_DEF
	ADD CONSTRAINT ALARM_DEF_FK1
	FOREIGN KEY (ALARM_GROUP_ID, LOADING_APPLICATION_ID)
	REFERENCES PROCESS_MONITOR (ALARM_GROUP_ID, LOADING_APPLICATION_ID)
;

-----------------------------
-- Manually Added:
ALTER TABLE PROCESS_MONITOR
	ADD CONSTRAINT PROCESS_MONITOR_FKLA
	FOREIGN KEY (LOADING_APPLICATION_ID)
	REFERENCES HDB_LOADING_APPLICATION(LOADING_APPLICATION_ID)
;
-----------------------------
