DROP INDEX DCP_TRANS_DATA_REC_IDX_SUFFIX;
DROP INDEX DCP_TRANS_ADDR_IDX_SUFFIX;
DROP INDEX DCP_TRANS_CHAN_IDX_SUFFIX;
DROP INDEX DCP_TRANS_MEDIUM_TYPE_SUFFIX;

DROP TABLE DCP_TRANS_DATA_SUFFIX;
DROP TABLE DCP_TRANS_SUFFIX;

CREATE TABLE DCP_TRANS_DATA_SUFFIX
(
	RECORD_ID NUMBER(18) NOT NULL,
	BLOCK_NUM INT NOT NULL,
	MSG_DATA VARCHAR2(4000) NOT NULL,
	PRIMARY KEY (RECORD_ID, BLOCK_NUM)
) &TBL_SPACE_SPEC;

CREATE TABLE DCP_TRANS_SUFFIX
(
	RECORD_ID NUMBER(18) NOT NULL,
	-- 'G' = GOES, 'L' = Data Logger, 'I' = Iridium.
	-- This field determines how the header should be parsed.
	MEDIUM_TYPE VARCHAR2(1) NOT NULL,
	MEDIUM_ID VARCHAR2(64) NOT NULL,
	LOCAL_RECV_TIME NUMBER(19) NOT NULL,
	TRANSMIT_TIME NUMBER(19) NOT NULL,
	FAILURE_CODES VARCHAR2(8) NOT NULL,
	-- Second of day when the transmit window started
	WINDOW_START_SOD INT,
	-- Transmit window length in seconds
	WINDOW_LENGTH INT,
	XMIT_INTERVAL INT,
	CARRIER_START NUMBER(19),
	CARRIER_STOP NUMBER(19),
	FLAGS INT NOT NULL,
	CHANNEL INT NOT NULL,
	BATTERY DOUBLE PRECISION,
    MSG_LENGTH INT NOT NULL,
    -- First block of data. Very long messages will have additional blocks.
    MSG_DATA VARCHAR(4000) NOT NULL,
	PRIMARY KEY (RECORD_ID)
) &TBL_SPACE_SPEC;

ALTER TABLE DCP_TRANS_DATA_SUFFIX
    ADD CONSTRAINT DCP_TRANS_DATA_FK_SUFFIX
	FOREIGN KEY (RECORD_ID)
    REFERENCES DCP_TRANS_SUFFIX (RECORD_ID)
;

CREATE INDEX DCP_TRANS_DATA_REC_IDX_SUFFIX ON DCP_TRANS_DATA_SUFFIX(RECORD_ID) &TBL_SPACE_SPEC;
CREATE INDEX DCP_TRANS_ADDR_IDX_SUFFIX ON DCP_TRANS_SUFFIX(MEDIUM_TYPE, MEDIUM_ID) &TBL_SPACE_SPEC;
CREATE INDEX DCP_TRANS_CHAN_IDX_SUFFIX ON DCP_TRANS_SUFFIX(CHANNEL) &TBL_SPACE_SPEC;
CREATE INDEX DCP_TRANS_MEDIUM_TYPE_SUFFIX ON DCP_TRANS_SUFFIX(MEDIUM_TYPE) &TBL_SPACE_SPEC;

