/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ilex_jni_SignalTrapper */

#ifndef _Included_ilex_jni_SignalTrapper
#define _Included_ilex_jni_SignalTrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ilex_jni_SignalTrapper
 * Method:    wasSignalSeen
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ilex_jni_SignalTrapper_wasSignalSeen
  (JNIEnv *, jclass, jint);

/*
 * Class:     ilex_jni_SignalTrapper
 * Method:    trapSignal
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_ilex_jni_SignalTrapper_trapSignal
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     ilex_jni_SignalTrapper
 * Method:    resetSignal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ilex_jni_SignalTrapper_resetSignal
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
