


CREATE ROLE "OTSDB_USER"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
COMMENT ON ROLE "OTSDB_USER" IS 'Read access to all Open TSDB Tables';


CREATE ROLE "OTSDB_DATA_ACQ" LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "OTSDB_USER" TO "OTSDB_DATA_ACQ";
COMMENT ON ROLE "OTSDB_DATA_ACQ" IS 'Data Acquisition - write access to time series tables.';


CREATE ROLE "OTSDB_COMP_EXEC" LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "OTSDB_DATA_ACQ" TO "OTSDB_COMP_EXEC";
COMMENT ON ROLE "OTSDB_COMP_EXEC" IS 'Execute computations - write ts data, read/write tasklist';


CREATE ROLE "OTSDB_MGR"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "OTSDB_COMP_EXEC" TO "OTSDB_MGR";
COMMENT ON ROLE "OTSDB_MGR" IS 'Manager - full R/W access to meta data';

CREATE ROLE "OTSDB_ADMIN"
  NOSUPERUSER INHERIT NOCREATEDB CREATEROLE NOREPLICATION;
GRANT "OTSDB_MGR" TO "OTSDB_ADMIN";
COMMENT ON ROLE "OTSDB_ADMIN" IS 'Full access to all tables. Can create other roles for users.';

