/*
* Where Applicable, Copyright 2024 OpenDCS Consortium or its contributors.
*
* Licensed under the Apache License, Version 2.0 (the "License"); you may not
* use this file except in compliance with the License. You may obtain a copy
* of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations
* under the License.
*/

package lrgs.gui;

/**
 * Expect Errors about OpenDcsVersion class not being found.
 * It is generated by the build and may not be correctly picked up by
 * your IDE.
 */


import org.opendcs.utils.OpenDcsVersion;

public final class LrgsBuild
{
	public static final String buildDate = OpenDcsVersion.COMMIT_HASH;
	public static final String version = OpenDcsVersion.VERSION;
	public static final String BUILD_COMMIT = OpenDcsVersion.COMMIT_HASH;

	private LrgsBuild()
	{
	}
}
