
JSRC = \
	SyncGui.java \
	District.java \
	DistrictDBSnap.java \
	DistrictPanel.java \
	DownloadReader.java \
	DownloadThread.java \
	FileList.java \
	FileListPanel.java \
	PlatList.java \
	PlatListEntry.java \
	PlatListPanel.java \
	SnapshotPanel.java \
	SyncConfig.java \
	SyncGuiFrame.java \
	SyncGuiFrame_AboutBox.java \
	TreePanel.java


JCLASS = ${JSRC:.java=.class}

all: ${JCLASS}

include ${DECODESSRCROOT}/Makefile.Common

depends:
	touch make.depend

install:

