/*
* Where Applicable, Copyright 2025 OpenDCS Consortium and/or its contributors
* 
* Licensed under the Apache License, Version 2.0 (the "License"); you may not
* use this file except in compliance with the License. You may obtain a copy
* of the License at
* 
*   http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software 
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations 
* under the License.
*/
package decodes.decoder;

/**
Base class for all exceptions generated by decoder modules.
*/
public class DecoderException extends decodes.util.DecodesException
{
	/**
	  Construct the exception.
	  @param msg the message
	*/
	public DecoderException(String msg)
	{
		super(msg);
	}
	
	/**
	  Construct the exception.
	  @param msg the message
	  @param cause the reason for failure
	*/
	public DecoderException(String msg, Throwable cause)
	{
		super(msg, cause);
	}

}

