CREATE TABLE DCP_TRANS_SUFFIX
(
	RECORD_ID INT NOT NULL UNIQUE,
	-- 'G' = GOES, 'L' = Data Logger, 'I' = Iridium.
	-- This field determines how the header should be parsed.
	MEDIUM_TYPE VARCHAR(1) NOT NULL,
	MEDIUM_ID VARCHAR(64) NOT NULL,
	LOCAL_RECV_TIME INT NOT NULL,
	TRANSMIT_TIME INT NOT NULL,
	FAILURE_CODES VARCHAR(8) NOT NULL,
	-- Second of day when the transmit window started
	WINDOW_START_SOD INT,
	-- Transmit window length in seconds
	WINDOW_LENGTH INT,
	XMIT_INTERVAL INT,
	CARRIER_START INT,
	CARRIER_STOP INT,
	FLAGS INT NOT NULL,
	CHANNEL INT NOT NULL,
	BATTERY FLOAT,
	-- Total message length, determines number of additional blocks
	-- required to store message.
	MSG_LENGTH INT NOT NULL,
	-- First block of data. Very long messages will have additional blocks.
	MSG_DATA VARCHAR(4000) NOT NULL,
	PRIMARY KEY (RECORD_ID)
);

CREATE TABLE DCP_TRANS_DATA_SUFFIX
(
	RECORD_ID INT NOT NULL REFERENCES DCP_TRANS_SUFFIX (RECORD_ID),
	BLOCK_NUM INT NOT NULL,
	MSG_DATA VARCHAR(4000) NOT NULL,
	PRIMARY KEY (RECORD_ID, BLOCK_NUM)
) ;


/* Create Indexes */

CREATE INDEX DCP_TRANS_DATA_REC_IDX_SUFFIX ON DCP_TRANS_DATA_SUFFIX (RECORD_ID);
CREATE INDEX DCP_TRANS_ADDR_IDX_SUFFIX ON DCP_TRANS_SUFFIX (MEDIUM_TYPE, MEDIUM_ID);
-- Used for GOES channel expansion in DCP Monitor
CREATE INDEX DCP_TRANS_CHAN_IDX_SUFFIX ON DCP_TRANS_SUFFIX  (CHANNEL);
CREATE INDEX DCP_TRANS_MEDIUM_TYPE_SUFFIX ON DCP_TRANS_SUFFIX (MEDIUM_TYPE);