/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ilex_jni_Debug */

#ifndef _Included_ilex_jni_Debug
#define _Included_ilex_jni_Debug
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ilex_jni_Debug
 * Method:    checkFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ilex_jni_Debug_checkFD
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
