#
#  $Id$
#
#  $Log$
#  Revision 1.1  2008/04/04 18:21:03  cvs
#  Added legacy code to repository
#
#  Revision 1.8  2004/09/08 10:10:08  mjmaloney
#  dev
#
#  Revision 1.7  2004/08/25 19:27:45  mjmaloney
#  dev
#
#  Revision 1.6  2004/08/09 15:07:35  mjmaloney
#  dev
#
#  Revision 1.5  2004/08/02 13:48:46  mjmaloney
#  dev
#
#  Revision 1.4  2004/07/28 15:37:27  mjmaloney
#  dev
#
#  Revision 1.3  2004/07/28 15:06:14  mjmaloney
#  dev
#
#  Revision 1.2  2004/02/09 21:07:30  mjmaloney
#  Complete GUI Prototype.
#
#  Revision 1.1  2004/02/09 01:57:04  mjmaloney
#  Created GUI Platform Wizard Prototype
#
#

JSRC = \
	PlatformWizard.java \
	Frame1.java \
	SampleDataPanel.java \
	StartPanel.java \
	WizardPanel.java \
	SitePanel.java \
	SelectDevicePanel.java \
	DefineSensorsPanel.java \
	ScriptEditPanel.java \
	PlatformPanel.java \
	SavePanel.java


JCLASS = ${JSRC:.java=.class}

all: ${JCLASS}

include ${DECODESSRCROOT}/Makefile.Common

depends:
	touch make.depend

install:

