#
#  $Id$
#
#  $State$
#
#  $Log$
#  Revision 1.1  2008/04/04 18:21:15  cvs
#  Added legacy code to repository
#
#  Revision 1.2  2001/03/01 13:37:21  mike
#  dev
#
#  Revision 1.1  2001/02/21 13:24:25  mike
#  Created
#
#

all: classes
	@echo upto date!!

include ${SRCROOT}/Makefile.Common
include ${SRCROOT}/Makefile.DependRules

#
# Java package prefix and source files:
#
JPKGPREFIX=lrgs.nledit.
JSRC=PasteBuffer.java NetlistEditFrame.java NetlistEditFrame_AboutBox.java \
	NetlistEditor.java NetworkListColumnModel.java NetworkListTable.java \
	NetworkListTableModel.java

classes: ${JCLASS}
	@echo finished making ${JCLASS}

install:

# DO NOT DELETE THIS LINE
