/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ilex_jni_EventContext */

#ifndef _Included_ilex_jni_EventContext
#define _Included_ilex_jni_EventContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ilex_jni_EventContext
 * Method:    newNativeContext
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ilex_jni_EventContext_newNativeContext
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ilex_jni_EventContext
 * Method:    freeNativeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ilex_jni_EventContext_freeNativeContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ilex_jni_EventContext
 * Method:    setNativeBacklog
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ilex_jni_EventContext_setNativeBacklog
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ilex_jni_EventContext
 * Method:    nextNativeEvent
 * Signature: (JLilex/jni/EventMsg;)Z
 */
JNIEXPORT jboolean JNICALL Java_ilex_jni_EventContext_nextNativeEvent
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
