/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ilex_jni_EventShmem */

#ifndef _Included_ilex_jni_EventShmem
#define _Included_ilex_jni_EventShmem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ilex_jni_EventShmem
 * Method:    attachNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ilex_jni_EventShmem_attachNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     ilex_jni_EventShmem
 * Method:    detachNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ilex_jni_EventShmem_detachNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
