#
#  $Id$
#
#  $State$
#
#  $Log$
#  Revision 1.1  2008/04/04 18:21:04  cvs
#  Added legacy code to repository
#
#  Revision 1.1  2001/07/24 02:16:57  mike
#  dev
#
#

JSRC = RoutingSpecThread.java

JCLASS = ${JSRC:.java=.class}

all: ${JCLASS}

include ${DECODESSRCROOT}/Makefile.Common

depends:
	touch make.depend

install:

