/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Parameter".
 */
export type Parameter = ExampleXORExamples &
  SchemaXORContent & {
    name: string;
    in: string;
    description?: string;
    required?: boolean;
    deprecated?: boolean;
    allowEmptyValue?: boolean;
    style?: string;
    explode?: boolean;
    allowReserved?: boolean;
    schema?: Schema | Reference;
    content?: {
      [k: string]: MediaType;
    };
    example?: unknown;
    examples?: {
      [k: string]: Example | Reference;
    };
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  } & Parameter1;
/**
 * Schema and content are mutually exclusive, at least one is required
 *
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "SchemaXORContent".
 */
export type SchemaXORContent = {
  [k: string]: unknown;
};
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "MediaType".
 */
export type MediaType = ExampleXORExamples & {
  schema?: Schema | Reference;
  example?: unknown;
  examples?: {
    [k: string]: Example | Reference;
  };
  encoding?: {
    [k: string]: Encoding;
  };
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Header".
 */
export type Header = ExampleXORExamples &
  SchemaXORContent & {
    description?: string;
    required?: boolean;
    deprecated?: boolean;
    allowEmptyValue?: boolean;
    style?: "simple";
    explode?: boolean;
    allowReserved?: boolean;
    schema?: Schema | Reference;
    content?: {
      [k: string]: MediaType;
    };
    example?: unknown;
    examples?: {
      [k: string]: Example | Reference;
    };
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
export type Parameter1 =
  | PathParameter
  | QueryParameter
  | HeaderParameter
  | CookieParameter;
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "SecurityScheme".
 */
export type SecurityScheme =
  | APIKeySecurityScheme
  | HTTPSecurityScheme
  | OAuth2SecurityScheme
  | OpenIdConnectSecurityScheme;
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "HTTPSecurityScheme".
 */
export type HTTPSecurityScheme = {
  scheme: string;
  bearerFormat?: string;
  description?: string;
  type: "http";
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
} & HTTPSecurityScheme1;
export type HTTPSecurityScheme1 =
  | {
      scheme?: string;
      [k: string]: unknown;
    }
  | {
      scheme?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };

/**
 * The description of OpenAPI v3.0.x Documents
 */
export interface HttpsSpecOpenapisOrgOas30Schema20241018 {
  openapi: string;
  info: Info;
  externalDocs?: ExternalDocumentation;
  servers?: Server[];
  security?: SecurityRequirement[];
  tags?: Tag[];
  paths: Paths;
  components?: Components;
  /**
   * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Info".
 */
export interface Info {
  title: string;
  description?: string;
  termsOfService?: string;
  contact?: Contact;
  license?: License;
  version: string;
  /**
   * This interface was referenced by `Info`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Contact".
 */
export interface Contact {
  name?: string;
  url?: string;
  email?: string;
  /**
   * This interface was referenced by `Contact`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "License".
 */
export interface License {
  name: string;
  url?: string;
  /**
   * This interface was referenced by `License`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "ExternalDocumentation".
 */
export interface ExternalDocumentation {
  description?: string;
  url: string;
  /**
   * This interface was referenced by `ExternalDocumentation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Server".
 */
export interface Server {
  url: string;
  description?: string;
  variables?: {
    [k: string]: ServerVariable;
  };
  /**
   * This interface was referenced by `Server`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "ServerVariable".
 */
export interface ServerVariable {
  enum?: string[];
  default: string;
  description?: string;
  /**
   * This interface was referenced by `ServerVariable`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "SecurityRequirement".
 */
export interface SecurityRequirement {
  [k: string]: string[];
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Tag".
 */
export interface Tag {
  name: string;
  description?: string;
  externalDocs?: ExternalDocumentation;
  /**
   * This interface was referenced by `Tag`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Paths".
 */
export interface Paths {}
/**
 * This interface was referenced by `Paths`'s JSON-Schema definition
 * via the `patternProperty` "^\/".
 *
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "PathItem".
 */
export interface PathItem {
  $ref?: string;
  summary?: string;
  description?: string;
  get?: Operation;
  put?: Operation;
  post?: Operation;
  delete?: Operation;
  options?: Operation;
  head?: Operation;
  patch?: Operation;
  trace?: Operation;
  servers?: Server[];
  parameters?: (Parameter | Reference)[];
  /**
   * This interface was referenced by `PathItem`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Operation".
 */
export interface Operation {
  tags?: string[];
  summary?: string;
  description?: string;
  externalDocs?: ExternalDocumentation;
  operationId?: string;
  parameters?: (Parameter | Reference)[];
  requestBody?: RequestBody | Reference;
  responses: Responses;
  callbacks?: {
    [k: string]: Callback | Reference;
  };
  deprecated?: boolean;
  security?: SecurityRequirement[];
  servers?: Server[];
  /**
   * This interface was referenced by `Operation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Example and examples are mutually exclusive
 *
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "ExampleXORExamples".
 */
export interface ExampleXORExamples {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Schema".
 */
export interface Schema {
  title?: string;
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: boolean;
  minimum?: number;
  exclusiveMinimum?: boolean;
  maxLength?: number;
  minLength?: number;
  pattern?: string;
  maxItems?: number;
  minItems?: number;
  uniqueItems?: boolean;
  maxProperties?: number;
  minProperties?: number;
  /**
   * @minItems 1
   */
  required?: [string, ...string[]];
  /**
   * @minItems 1
   */
  enum?: [unknown, ...unknown[]];
  type?: "array" | "boolean" | "integer" | "number" | "object" | "string";
  not?: Schema | Reference;
  allOf?: (Schema | Reference)[];
  oneOf?: (Schema | Reference)[];
  anyOf?: (Schema | Reference)[];
  items?: Schema | Reference;
  properties?: {
    [k: string]: Schema | Reference;
  };
  additionalProperties?: Schema | Reference | boolean;
  description?: string;
  format?: string;
  default?: unknown;
  nullable?: boolean;
  discriminator?: Discriminator;
  readOnly?: boolean;
  writeOnly?: boolean;
  example?: unknown;
  externalDocs?: ExternalDocumentation;
  deprecated?: boolean;
  xml?: XML;
  /**
   * This interface was referenced by `Schema`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Reference".
 */
export interface Reference {
  /**
   * This interface was referenced by `Reference`'s JSON-Schema definition
   * via the `patternProperty` "^\$ref$".
   */
  [k: string]: string;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Discriminator".
 */
export interface Discriminator {
  propertyName: string;
  mapping?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "XML".
 */
export interface XML {
  name?: string;
  namespace?: string;
  prefix?: string;
  attribute?: boolean;
  wrapped?: boolean;
  /**
   * This interface was referenced by `XML`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Example".
 */
export interface Example {
  summary?: string;
  description?: string;
  value?: unknown;
  externalValue?: string;
  /**
   * This interface was referenced by `Example`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Encoding".
 */
export interface Encoding {
  contentType?: string;
  headers?: {
    [k: string]: Header | Reference;
  };
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  explode?: boolean;
  allowReserved?: boolean;
  /**
   * This interface was referenced by `Encoding`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Parameter in path
 *
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "PathParameter".
 */
export interface PathParameter {
  in?: "path";
  style?: "matrix" | "label" | "simple";
  required: true;
  [k: string]: unknown;
}
/**
 * Parameter in query
 *
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "QueryParameter".
 */
export interface QueryParameter {
  in?: "query";
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  [k: string]: unknown;
}
/**
 * Parameter in header
 *
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "HeaderParameter".
 */
export interface HeaderParameter {
  in?: "header";
  style?: "simple";
  [k: string]: unknown;
}
/**
 * Parameter in cookie
 *
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "CookieParameter".
 */
export interface CookieParameter {
  in?: "cookie";
  style?: "form";
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "RequestBody".
 */
export interface RequestBody {
  description?: string;
  content: {
    [k: string]: MediaType;
  };
  required?: boolean;
  /**
   * This interface was referenced by `RequestBody`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Responses".
 */
export interface Responses {
  default?: Response | Reference;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Response".
 */
export interface Response {
  description: string;
  headers?: {
    [k: string]: Header | Reference;
  };
  content?: {
    [k: string]: MediaType;
  };
  links?: {
    [k: string]: Link | Reference;
  };
  /**
   * This interface was referenced by `Response`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Link".
 */
export interface Link {
  operationId?: string;
  operationRef?: string;
  parameters?: {
    [k: string]: unknown;
  };
  requestBody?: unknown;
  description?: string;
  server?: Server;
  /**
   * This interface was referenced by `Link`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Callback".
 */
export interface Callback {
  [k: string]: PathItem;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "Components".
 */
export interface Components {
  schemas?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Schema | Reference;
  };
  responses?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Response;
  };
  parameters?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Parameter;
  };
  examples?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Example;
  };
  requestBodies?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | RequestBody;
  };
  headers?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Header;
  };
  securitySchemes?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | SecurityScheme;
  };
  links?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Link;
  };
  callbacks?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Callback;
  };
  /**
   * This interface was referenced by `Components`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "APIKeySecurityScheme".
 */
export interface APIKeySecurityScheme {
  type: "apiKey";
  name: string;
  in: "header" | "query" | "cookie";
  description?: string;
  /**
   * This interface was referenced by `APIKeySecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "OAuth2SecurityScheme".
 */
export interface OAuth2SecurityScheme {
  type: "oauth2";
  flows: OAuthFlows;
  description?: string;
  /**
   * This interface was referenced by `OAuth2SecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "OAuthFlows".
 */
export interface OAuthFlows {
  implicit?: ImplicitOAuthFlow;
  password?: PasswordOAuthFlow;
  clientCredentials?: ClientCredentialsFlow;
  authorizationCode?: AuthorizationCodeOAuthFlow;
  /**
   * This interface was referenced by `OAuthFlows`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "ImplicitOAuthFlow".
 */
export interface ImplicitOAuthFlow {
  authorizationUrl: string;
  refreshUrl?: string;
  scopes: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `ImplicitOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "PasswordOAuthFlow".
 */
export interface PasswordOAuthFlow {
  tokenUrl: string;
  refreshUrl?: string;
  scopes: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `PasswordOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "ClientCredentialsFlow".
 */
export interface ClientCredentialsFlow {
  tokenUrl: string;
  refreshUrl?: string;
  scopes: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `ClientCredentialsFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "AuthorizationCodeOAuthFlow".
 */
export interface AuthorizationCodeOAuthFlow {
  authorizationUrl: string;
  tokenUrl: string;
  refreshUrl?: string;
  scopes: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `AuthorizationCodeOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * This interface was referenced by `HttpsSpecOpenapisOrgOas30Schema20241018`'s JSON-Schema
 * via the `definition` "OpenIdConnectSecurityScheme".
 */
export interface OpenIdConnectSecurityScheme {
  type: "openIdConnect";
  openIdConnectUrl: string;
  description?: string;
  /**
   * This interface was referenced by `OpenIdConnectSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
