#
#  $Id$
#
#  $Log$
#  Revision 1.1  2008/04/04 18:21:04  cvs
#  Added legacy code to repository
#
#  Revision 1.1  2004/04/29 01:10:20  mjmaloney
#  Created.
#

JSRC = \
	RoutingMonitor.java \
	RoutingDirMonitor.java \
	RoutingSpecStatus.java \
	BadStatusFile.java


JCLASS = ${JSRC:.java=.class}

all: ${JCLASS}

include ${DECODESSRCROOT}/Makefile.Common

depends:
	touch make.depend

install:

