#
#  $Id$
#
#  $Source$
#
#  $State$
#
#  $Log$
#  Revision 1.1  2008/04/04 18:21:08  cvs
#  Added legacy code to repository
#
#  Revision 1.2  2001/08/24 19:45:58  mike
#  Added StdAppSettings
#
#  Revision 1.1  1999/12/04 12:34:06  mike
#  Initial checkin
#
#

JSRC = ApplicationSettings.java BooleanToken.java IntegerToken.java \
	Main.java StringArrayIterator.java StringToken.java Token.java \
	TokenOptions.java util.java StdAppSettings.java

JCLASS = ${JSRC:.java=.class}

all: ${JCLASS}

include ${ILEXSRCROOT}/Makefile.Common

depends:
	touch make.depend

install:

