FROM docker.io/rockylinux/rockylinux:9.3.20231119

RUN mkdir /opendcs
RUN dnf -y update
RUN dnf -y install wget
RUN dnf -y install java-1.8.0-openjdk.x86_64

COPY ./docker-config/ /opendcs/
COPY ./build/tmp/opendcs-installer.jar /opendcs/opendcs-installer.jar
COPY ./build/distributions/opendcs-rest-api-jetty.tgz /opendcs-api/opendcs-rest-api-jetty.tgz
RUN java -jar /opendcs/opendcs-installer.jar /opendcs/auto-installation-script.xml

CMD ["bash","-c", "tar -xvf /opendcs-api/opendcs-rest-api-jetty.tgz -C /opendcs-api/ && cd /opendcs-api/bin/ && chmod +x ./start.sh && ./start.sh"]
