FROM postgres:12.17

RUN apt-get update
RUN apt-get install openjdk-17-jre -y

COPY ./docker-config/ /opendcs/
COPY ./build/tmp/opendcs-installer.jar /opendcs/opendcs-installer.jar
COPY ./docker-config/InstallTsdbSchemaDocker.sh /docker-entrypoint-initdb.d/InstallTsdbSchemaDocker.sh
RUN chmod 777 /docker-entrypoint-initdb.d/InstallTsdbSchemaDocker.sh
RUN java -jar /opendcs/opendcs-installer.jar /opendcs/auto-installation-script.xml
RUN chmod a+w /opendcs/schema/opendcs-pg/
RUN chmod -R a+x /opendcs/schema/opendcs-pg/*
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

