/*
* Where Applicable, Copyright 2025 OpenDCS Consortium and/or its contributors
*
* Licensed under the Apache License, Version 2.0 (the "License"); you may not
* use this file except in compliance with the License. You may obtain a copy
* of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations
* under the License.
*/
package ilex.util;

/**
* This class forms the base for all exceptions generated by the Ilex, LRGS,
* and DECODES packages.
* This version is simply a place-holder. In the future, we will add a logging
* capability to the constructor so that all thrown exceptions can optionally
* be logged.
*/
public class IlexException extends Exception
{
	/**
	* Constructor
	* @param msg the message
	*/
	public IlexException( String msg )
	{
		super(msg);
	}

	public IlexException(String msg, Throwable cause)
	{
		super(msg, cause);
	}
}
