---
name: docker testing
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: write
        packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6.0.0
        with:
          tags: |
            type=sha
            type=ref,event=tag
            type=raw,value=${{env.VERSION}}
            type=schedule,pattern=${{inputs.branch}}-{{date 'YYYY.MM.DD'}}
            type=schedule,pattern=${{inputs.branch}}-{{date 'YYYY.MM.DD-hhmmss'}}


      - name: create docker images
        uses: docker/bake-action@v7
        with:
          files: |
            docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: lrgs,compproc,compdepends,routingscheduler,web-api,migration
          push: false
        # run: |
        #   REPO=`echo ${{github.repository_owner}} | tr  '[:upper:]' '[:lower:]'`
        #   ./build_docker.sh ghcr.io/${REPO} ${VERSION} "${{steps.meta.outputs.tags}}"
      
      # - name: Push images
      #   run: |
      #     REPO=`echo ${{github.repository_owner}} | tr  '[:upper:]' '[:lower:]'`
      #     images=("lrgs"  "routingscheduler"  "compproc" "compdepends" "web-api" "migration")
      #     for image in ${images[@]}; do
      #       while IFS= read -r version; do
      #         docker push ghcr.io/${REPO}/${image}:${version}
      #       done <<< "${{steps.meta.outputs.tags}}"
      #     done