
/* Drop Tables */

DROP TABLE IF EXISTS ALARM_DEF;
DROP TABLE IF EXISTS PROCESS_MONITOR;
DROP TABLE IF EXISTS FILE_MONITOR;
DROP TABLE IF EXISTS EMAIL_ADDR;
DROP TABLE IF EXISTS ALARM_GROUP;




/* Create Tables */

CREATE TABLE ALARM_DEF
(
	ALARM_DEF_ID int NOT NULL UNIQUE,
	ALARM_GROUP_ID int NOT NULL,
	LOADING_APPLICATION_ID int NOT NULL,
	PRIORITY int NOT NULL,
	PATTERN varchar(256),
	PRIMARY KEY (ALARM_DEF_ID)
) WITHOUT OIDS;


CREATE TABLE ALARM_GROUP
(
	ALARM_GROUP_ID int NOT NULL UNIQUE,
	ALARM_GROUP_NAME varchar(32) NOT NULL UNIQUE,
	LAST_MODIFIED bigint NOT NULL,
	PRIMARY KEY (ALARM_GROUP_ID)
) WITHOUT OIDS;


CREATE TABLE EMAIL_ADDR
(
	ALARM_GROUP_ID int NOT NULL,
	ADDR varchar(256) NOT NULL,
	PRIMARY KEY (ALARM_GROUP_ID, ADDR)
) WITHOUT OIDS;


CREATE TABLE FILE_MONITOR
(
	ALARM_GROUP_ID int NOT NULL,
	PATH varchar(256) NOT NULL,
	PRIORITY int NOT NULL,
	MAX_FILES int,
	MAX_FILES_HINT varchar(128),
	-- Maximum Last Modify Time
	MAX_LMT varchar(32),
	MAX_LMT_HINT varchar(128),
	ALARM_ON_DELETE boolean,
	ON_DELETE_HINT varchar(128),
	MAX_SIZE bigint,
	MAX_SIZE_HINT varchar(128),
	ALARM_ON_EXISTS boolean,
	ON_EXISTS_HINT varchar(128),
	ENABLED boolean,
	PRIMARY KEY (ALARM_GROUP_ID, PATH)
) WITHOUT OIDS;


CREATE TABLE PROCESS_MONITOR
(
	ALARM_GROUP_ID int NOT NULL,
	LOADING_APPLICATION_ID int NOT NULL,
	ENABLED boolean,
	PRIMARY KEY (ALARM_GROUP_ID, LOADING_APPLICATION_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE PROCESS_MONITOR
	ADD FOREIGN KEY (ALARM_GROUP_ID)
	REFERENCES ALARM_GROUP (ALARM_GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FILE_MONITOR
	ADD FOREIGN KEY (ALARM_GROUP_ID)
	REFERENCES ALARM_GROUP (ALARM_GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMAIL_ADDR
	ADD FOREIGN KEY (ALARM_GROUP_ID)
	REFERENCES ALARM_GROUP (ALARM_GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ALARM_DEF
	ADD FOREIGN KEY (ALARM_GROUP_ID, LOADING_APPLICATION_ID)
	REFERENCES PROCESS_MONITOR (ALARM_GROUP_ID, LOADING_APPLICATION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON COLUMN FILE_MONITOR.MAX_LMT IS 'Maximum Last Modify Time';



