--------------------------------------------------------------------------
-- Create roles for OPENDCS Time Series Database under Oracle           --
--
-- Cove Software, LLC
--------------------------------------------------------------------------
set echo on
spool roles.log

@@defines.sql

-- ROLE "OTSDB_USER" IS 'Read access to all Open TSDB Tables';
CREATE ROLE OTSDB_USER;

-- ROLE "OTSDB_DATA_ACQ" IS 'Data Acquisition - write access to time series tables.';
-- In Postgres, this is a login role
CREATE ROLE OTSDB_DATA_ACQ;
GRANT OTSDB_USER TO OTSDB_DATA_ACQ;

-- ROLE "OTSDB_COMP_EXEC" IS 'Execute computations - write ts data, read/write tasklist';
-- In Postgres, this is a login role
CREATE ROLE OTSDB_COMP_EXEC;
GRANT OTSDB_DATA_ACQ TO OTSDB_COMP_EXEC;

-- ROLE "OTSDB_MGR" IS 'Manager - full R/W access to meta data';
CREATE ROLE OTSDB_MGR;
GRANT OTSDB_DATA_ACQ TO OTSDB_MGR;

-- ROLE "OTSDB_ADMIN" IS 'Full access to all tables. Can create other roles for users.';
CREATE ROLE OTSDB_ADMIN;
GRANT OTSDB_MGR TO OTSDB_ADMIN;

GRANT CREATE SESSION,RESOURCE,CONNECT TO OTSDB_ADMIN;
GRANT ALTER ANY TABLE,CREATE ANY TABLE,CREATE ANY INDEX,CREATE ANY SEQUENCE,
  CREATE ANY VIEW,CREATE ANY PROCEDURE,CREATE ANY TRIGGER,CREATE ANY JOB,
  CREATE PUBLIC SYNONYM,DROP PUBLIC SYNONYM
  TO OTSDB_ADMIN;

CREATE USER &TSDB_ADM_SCHEMA IDENTIFIED BY &TSDB_ADM_PASSWD
  DEFAULT TABLESPACE &TBL_SPACE_DATA QUOTA UNLIMITED ON &TBL_SPACE_DATA
  TEMPORARY TABLESPACE &TBL_SPACE_TEMP
  PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT OTSDB_ADMIN TO &TSDB_ADM_SCHEMA;

-- GRANT CREATE SESSION,RESOURCE,CONNECT TO &TSDB_ADM_SCHEMA;
-- GRANT ALTER ANY TABLE,CREATE ANY TABLE,CREATE ANY INDEX,CREATE ANY SEQUENCE,
--   CREATE ANY VIEW,CREATE ANY PROCEDURE,CREATE ANY TRIGGER,CREATE ANY JOB,
--   CREATE PUBLIC SYNONYM,DROP PUBLIC SYNONYM
--   TO &TSDB_ADM_SCHEMA;

ALTER USER &TSDB_ADM_SCHEMA DEFAULT ROLE ALL;

--
-- TODO: Create a normal user
--

spool off
exit;
